services:
  cgdf_api:
    container_name: cgdf_prod
    build:
      context: .
      dockerfile: Dockerfile_prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
