services:
  cgdf_api:
    container_name: cgdf_dev
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
    volumes:
      - ./app:/app